# Generated by Django 3.2 on 2021-04-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
