# Generated by Django 3.2 on 2021-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
